### ISSUE TITLE
Navigation property attachment

### ISSUE THREAD

**Issue by radissoa** [peterjohnlawrence/com.inova8.odata2sparql.v4#200]
Hello Peter,

You did a great job with odata2sparql. I'm looking for a small clarification on something.
Here is the situation I am looking at : 
It looks like you attach a navigation property based on the rdfs:domain of the corresponding predicate, that means that for example you attach skos:broader navigation property to skos:Concept entity set. The thing is if I want to use skos:broader on another class, let's call :Item it is not attach to it. Note that apart from that :Item is a subclassOf skos:Concept.

Hence to get the broader concept of an item I am obligated to look for it through GET /skos_Concept('myItem')/skos_broader instead of GET /Item('myItem')/skos_broader which is more intuitive.

I don't think this is a bug and one solution could be to add my :Item as a rdfs:domain for skos:broader but this does not feel right and does not scale up when other situations like this occur for other properties in my ontology. 

Do you have any better solution than mine for this issue ?

Best regards,
Alexis

**Comment by radissoa** [comment]
Sadly, the metadata does not show skos_broader as a navigation property of :Item.

**Comment by peterjohnlawrence** [comment]
Is it showing it as a navigationproperty of skos_concept?

*Peter J. Lawrence*
*inova8*
*Providing answers for users' information questions*
*Mobile:*  +44 7546 095977 | +1 330 631 3772 | *Phone:* +44 1298 872375 |
*Skype:* PeterJLawrence
*Email:* ***@***.*** |  *Web:* www.inova8.com
*LinkedIn: *

*http://www.linkedin.com/in/peterjohnlawrence
<http://www.linkedin.com/in/peterjohnlawrence>*

**Comment by peterjohnlawrence** [comment]
Can you share the $metadata with me, if that is possible. Thanks
*Peter J. Lawrence*
*inova8*
*Providing answers for users' information questions*
*Mobile:*  +44 7546 095977 | +1 330 631 3772 | *Phone:* +44 1298 872375 |
*Skype:* PeterJLawrence
*Email:* ***@***.*** |  *Web:* www.inova8.com
*LinkedIn: *

*http://www.linkedin.com/in/peterjohnlawrence
<http://www.linkedin.com/in/peterjohnlawrence>*

**Comment by radissoa** [comment]
I sent it on your email.
Alexis

**Comment by peterjohnlawrence** [comment]
This has now been fixed in #205.
All superClass properties *should* have been inherited but there were certain cases when they were not
